### ISSUE TITLE
Package release request

### ISSUE THREAD

**Issue by gallardoalba** [HajkD/metablastr#14]
Hi,
would be possible to provide a [package release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)? It is required for creating the conda package.

Regards

**Comment by HajkD** [comment]
Done! :)

Please find the release here: https://github.com/drostlab/metablastr/releases/tag/v0.3.2

Thank you very much for pushing this forward!

Cheers,
Hajk

**Comment by gallardoalba** [comment]
Thanks a lot!
