### ISSUE TITLE
blast_nt for nucleotide against NCBI database

### ISSUE THREAD

**Issue by antoine4ucsd** [HajkD/metablastr#15]
Hello
thank you for developping this set of tools
I am trying to run my nucleotide sequences againts NCBI database
From your vignette, it should be blast_n()?
but the function is not available is the version of metablastr I just installed with
```
devtools::install_github("drostlab/metablastr", build_vignettes = TRUE, dependencies = TRUE)
```

do you have an alternative to this function  for nucleotides?
https://drostlab.github.io/metablastr/reference/blast_protein_to_nr_database.html

does the database need to be stored locally? advices?

thank you!

**Comment by HajkD** [comment]
Hi @antoine4ucsd 

Happy to hear that `metablastr` is useful for your research.

Currently, there is no analog to the `blast_protein_to_nr_database()` function for nucleotides implemented yet, but I can put it on the TODO list.

As for the NR database, yes it would need to be locally stored.

I hope this helps.

Cheers,
Hajk

**Comment by antoine4ucsd** [comment]
thank you. I figured an alternative approach (terminal).

**Comment by HajkD** [comment]
__Just as a comment__: the strength (and purpose) of `metablastr` is not running the search itself (this can be done easily via the terminal), but rather how to process and pipe the BLAST result output back into an R session for downstream analytics with `dplyr` and other `tidy tools`.
