### ISSUE TITLE
Reg: Reciprocal hits from already run blast outcomes

### ISSUE THREAD

**Issue by harish0201** [HajkD/metablastr#9]
Hi!

I have performed the following to obtain blast format 6 tabular format:

1. A vs B with Diamond
2. B vs A with Diamond

I read AvB.hits and BvA.hits using read_blast() function. Will it be possible to identify the reciprocal hits? Or should I rerun the searches with metablastr?

**Comment by HajkD** [comment]
Hi Harish

Many thanks for contacting me.

Could you please provide me a small example script?

Are you using `rdiamond` or `metablastr` or both?

This will help me to help you better.

Cheers,
Hajk

**Comment by harish0201** [comment]
Hi!

These were run directly via diamond. At this stage, I was not using rdiamond or metablastr.

So basically, I ran diamond to obtain hits in the tabular (6) format, which is the default diamond output, and reading them via read_blast() function under metablastr.

**Comment by HajkD** [comment]
Hi,

Do you want to try [read_diamond()](https://drostlab.github.io/rdiamond/reference/read_diamond.html) in my R package [rdiamond](https://github.com/drostlab/rdiamond)?

Cheers,
Hajk

**Comment by HajkD** [comment]
Passing an existing BLAST/DIAMOND output into the `blast_reciprocal_best_hit()` function is currently not possible and I can see this as a feature request.

**Comment by harish0201** [comment]
Hi!

Sorry, I didn't get any notifications from GitHub. I'll play around with rdiamond!
